import {
  DESKTOP_ASSISTANT_EXECUTOR_PROMPT,
  DESKTOP_ASSISTANT_PLANNER_PROMPT,
  DESKTOP_ASSISTANT_SYSTEM_PROMPT
} from "@my-pet/shared-prompts";

export const promptBundle = {
  system: DESKTOP_ASSISTANT_SYSTEM_PROMPT,
  planner: DESKTOP_ASSISTANT_PLANNER_PROMPT,
  executor: DESKTOP_ASSISTANT_EXECUTOR_PROMPT
};
